"""add users and repository ownership

Every repository now belongs to a user. Rows that predate this have no owner
and cannot be given one, so the upgrade DELETES them (cascading to their jobs,
files, and tours). Before this migration nothing could be analysed, so those
rows only ever held failed placeholder jobs.

Revision ID: b79c112a166b
Revises: 4ea5f282b445
Create Date: 2026-09-11 07:14:22.155511
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b79c112a166b'
down_revision: str | None = '4ea5f282b445'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_sessions_token_hash'))
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # Hand-added: owner_id is NOT NULL, and existing rows have no owner to give
    # it. See the module docstring.
    op.execute('DELETE FROM repositories')
    op.add_column('repositories', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_repositories_source_url'), 'repositories', type_='unique')
    op.create_unique_constraint('uq_repositories_owner_id_source_url', 'repositories', ['owner_id', 'source_url'])
    op.create_foreign_key(op.f('fk_repositories_owner_id_users'), 'repositories', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_repositories_owner_id_users'), 'repositories', type_='foreignkey')
    op.drop_constraint('uq_repositories_owner_id_source_url', 'repositories', type_='unique')
    # Hand-added: two users may each have a row for the same URL, which the
    # old URL-only constraint forbids. Keep the oldest row per URL.
    op.execute(
        'DELETE FROM repositories newer USING repositories older '
        'WHERE newer.source_url = older.source_url AND newer.id > older.id'
    )
    op.create_unique_constraint(op.f('uq_repositories_source_url'), 'repositories', ['source_url'], postgresql_nulls_not_distinct=False)
    op.drop_column('repositories', 'owner_id')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
