"""initial schema

Revision ID: 4ea5f282b445
Revises: 
Create Date: 2026-08-24 12:27:47.580515
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '4ea5f282b445'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('last_analyzed_commit', sa.String(length=40), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'ANALYZING', 'READY', 'FAILED', name='repository_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories')),
    sa.UniqueConstraint('source_url', name='uq_repositories_source_url')
    )
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='job_state'), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_analysis_jobs_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_jobs'))
    )
    op.create_index(op.f('ix_analysis_jobs_repository_id'), 'analysis_jobs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_task_id'), 'analysis_jobs', ['task_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('last_changed_commit', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_files_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files')),
    sa.UniqueConstraint('repository_id', 'path', name='uq_files_repository_id_path')
    )
    op.create_index(op.f('ix_files_repository_id'), 'files', ['repository_id'], unique=False)
    op.create_table('tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('persona', sa.Enum('NEW_CONTRIBUTOR', 'BUG_FIXER', 'FEATURE_BUILDER', 'REVIEWER', name='persona'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_tours_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tours'))
    )
    op.create_index(op.f('ix_tours_repository_id'), 'tours', ['repository_id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('target_file_id', sa.Integer(), nullable=False),
    sa.Column('edge_type', sa.Enum('IMPORT', 'CALL', name='edge_type'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_graph_edges_repository_id_repositories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], name=op.f('fk_graph_edges_source_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_file_id'], ['files.id'], name=op.f('fk_graph_edges_target_file_id_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_edges'))
    )
    op.create_index(op.f('ix_graph_edges_repository_id'), 'graph_edges', ['repository_id'], unique=False)
    op.create_index('ix_graph_edges_repository_id_source', 'graph_edges', ['repository_id', 'source_file_id'], unique=False)
    op.create_table('tour_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('cited_line_start', sa.Integer(), nullable=True),
    sa.Column('cited_line_end', sa.Integer(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_tour_steps_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], name=op.f('fk_tour_steps_tour_id_tours'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tour_steps')),
    sa.UniqueConstraint('tour_id', 'order_index', name='uq_tour_steps_tour_id_order')
    )
    op.create_index(op.f('ix_tour_steps_tour_id'), 'tour_steps', ['tour_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_steps_tour_id'), table_name='tour_steps')
    op.drop_table('tour_steps')
    op.drop_index('ix_graph_edges_repository_id_source', table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_repository_id'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_tours_repository_id'), table_name='tours')
    op.drop_table('tours')
    op.drop_index(op.f('ix_files_repository_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_analysis_jobs_task_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_repository_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_table('repositories')
    # ### end Alembic commands ###
